/** @type {import('tailwindcss').Config} */
import animate from 'tailwindcss-animate'

export default {
	darkMode: ['class'],
	content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
	theme: {
		extend: {
			colors: {
				primary: 'var(--primary)',
				'on-primary': 'var(--on-primary)',
				'primary-container': 'var(--primary-container)',
				'on-primary-container': 'var(--on-primary-container)',
				secondary: 'var(--secondary)',
				'on-secondary': 'var(--on-secondary)',
				'secondary-container': 'var(--secondary-container)',
				'on-secondary-container': 'var(--on-secondary-container)',
				tertiary: 'var(--tertiary)',
				'on-tertiary': 'var(--on-tertiary)',
				'tertiary-container': 'var(--tertiary-container)',
				'on-tertiary-container': 'var(--on-tertiary-container)',
				error: 'var(--error)',
				'on-error': 'var(--on-error)',
				'error-container': 'var(--error-container)',
				'on-error-container': 'var(--on-error-container)',
				background: 'var(--background)',
				'on-background': 'var(--on-background)',
				surface: 'var(--surface)',
				'on-surface': 'var(--on-surface)',
				'surface-variant': 'var(--surface-variant)',
				'on-surface-variant': 'var(--on-surface-variant)',
				outline: 'var(--outline)',
				'outline-variant': 'var(--outline-variant)',
				shadow: 'var(--shadow)',
				scrim: 'var(--scrim)',
				'inverse-surface': 'var(--inverse-surface)',
				'inverse-on-surface': 'var(--inverse-on-surface)',
				'inverse-primary': 'var(--inverse-primary)',
				'primary-fixed': 'var(--primary-fixed)',
				'on-primary-fixed': 'var(--on-primary-fixed)',
				'primary-fixed-dim': 'var(--primary-fixed-dim)',
				'on-primary-fixed-variant': 'var(--on-primary-fixed-variant)',
				'secondary-fixed': 'var(--secondary-fixed)',
				'on-secondary-fixed': 'var(--on-secondary-fixed)',
				'secondary-fixed-dim': 'var(--secondary-fixed-dim)',
				'on-secondary-fixed-variant': 'var(--on-secondary-fixed-variant)',
				'tertiary-fixed': 'var(--tertiary-fixed)',
				'on-tertiary-fixed': 'var(--on-tertiary-fixed)',
				'tertiary-fixed-dim': 'var(--tertiary-fixed-dim)',
				'on-tertiary-fixed-variant': 'var(--on-tertiary-fixed-variant)',
				'surface-dim': 'var(--surface-dim)',
				'surface-bright': 'var(--surface-bright)',
				'surface-container-lowest': 'var(--surface-container-lowest)',
				'surface-container-low': 'var(--surface-container-low)',
				'surface-container': 'var(--surface-container)',
				'surface-container-high': 'var(--surface-container-high)',
				'surface-container-highest': 'var(--surface-container-highest)',
			},
			borderRadius: {
				none: 'var(--radius-none)',
				sm: 'var(--radius-sm)',
				md: 'var(--radius-md)',
				lg: 'var(--radius-lg)',
				xl: 'var(--radius-xl)',
				full: 'var(--radius-full)',
			},
			boxShadow: {
				'elevation-1': 'var(--layout-shadow-elevation)',
				'elevation-2': 'var(--layout-shadow-elevation-lg)',
			},
			animation: {
				'accordion-down': 'accordion-down 0.2s ease-out',
				'accordion-up': 'accordion-up 0.2s ease-out',
			},
			fontFamily: {
				// Common body/content font
				body: ['DM Sans', 'sans-serif'],
				content: ['DM Sans', 'sans-serif'],
				// Typography token-specific families
				display: ['Cinzel', 'serif'],
				heading: ['Cardo', 'serif'],
				label: ['Cardo', 'serif'],
			},
			fontSize: {
				'display-hero': 'var(--font-size-display-hero)',
				'display-l': 'var(--font-size-display-l)',
				'display-m': 'var(--font-size-display-m)',
				'display-s': 'var(--font-size-display-s)',
				'heading-l': 'var(--font-size-heading-l)',
				'heading-m': 'var(--font-size-heading-m)',
				'heading-s': 'var(--font-size-heading-s)',
				'title-l': 'var(--font-size-title-l)',
				'title-m': 'var(--font-size-title-m)',
				'title-s': 'var(--font-size-title-s)',
				'body-l': 'var(--font-size-body-l)',
				'body-m': 'var(--font-size-body-m)',
				'body-s': 'var(--font-size-body-s)',
				'label-l': 'var(--font-size-label-l)',
				'label-m': 'var(--font-size-label-m)',
				'label-s': 'var(--font-size-label-s)',
			},
			spacing: {
				none: 'var(--spacing-none)',
				xxs: 'var(--spacing-xxs)',
				xs: 'var(--spacing-xs)',
				sm: 'var(--spacing-sm)',
				md: 'var(--spacing-md)',
				lg: 'var(--spacing-lg)',
				xl: 'var(--spacing-xl)',
				xxl: 'var(--spacing-xxl)',
			},
			gap: {
				none: 'var(--gap-none)',
				xxs: 'var(--gap-xxs)',
				xs: 'var(--gap-xs)',
				sm: 'var(--gap-sm)',
				md: 'var(--gap-md)',
				lg: 'var(--gap-lg)',
				xl: 'var(--gap-xl)',
				xxl: 'var(--gap-xxl)',
			},
			zIndex: {
				negative: 'var(--z-index-negative)',
				background: 'var(--z-index-background)',
				default: 'var(--z-index-default)',
				dropdown: 'var(--z-index-dropdown)',
				sticky: 'var(--z-index-sticky)',
				fixed: 'var(--z-index-fixed)',
				modalBackdrop: 'var(--z-index-modal-backdrop)',
				offcanvas: 'var(--z-index-offcanvas)',
				modal: 'var(--z-index-modal)',
				popover: 'var(--z-index-popover)',
				tooltip: 'var(--z-index-tooltip)',
			},
		},
	},
	plugins: [animate],
}
